version: '3.7'

services:
  dbt:
    image: xemuliam/dbt:latest
    container_name: dbt
    restart: always
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./dbt:/dbt

  redash:
    image: redash/redash:latest
    container_name: redash
    restart: always
    depends_on:
      - postgres
    ports:
      - "5000:5000"
    environment:
      REDASH_LOG_LEVEL: "INFO"
      REDASH_REDIS_URL: "redis://redis:6379/0"
      REDASH_DATABASE_URL: "postgresql://postgres:postgres@postgres:5432/traffic-data"
