traffic_db_profile:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost  
      port: 5432       
      user: postgres     
      pass: postgres     
      dbname: postgres     
      schema: raw
      threads: 1       
